name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ github.repository_owner }}

      - name: Set up Git authentication
        run: |
          git config --global user.name "gunjae-yoon"
          git config --global user.email "rnswo42b@gmail.com"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/gunjae-yoon/gunjae-yoon.git

      - name: Commit & Push
        run: |
          git add -A .
          git commit -m "generated"
          git push origin HEAD:main
