name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT for authentication
        run: |
          git config user.name "gunjae-yoon"
          git config user.email "rnswo42b@gmail.com"
          git add -A .
          git commit -m "generated"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY).git HEAD:main
